name: Cleanup Preview Env

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  architect_destroy_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
      - name: Architect Destroy Preview
        uses: architect-team/destroy-preview@v1.0.1
        with:
          email: ${{ secrets.ARCHITECT_ACCT_EMAIL }}
          password: ${{ secrets.ARCHITECT_ACCT_PASSWORD }}
          account: architect
          environment: auth-preview-${{ github.head_ref }}
          component_name: architect-auth
