name: Create Preview Env

on:
  pull_request:
    branches:
      - master

jobs:
  architect_create_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Architect Create Preview
        uses: architect-team/create-preview@v1.0.1
        with:
          email: ${{ secrets.ARCHITECT_ACCT_EMAIL }}
          password: ${{ secrets.ARCHITECT_ACCT_PASSWORD }}
          account: architect
          platform: public
          environment: auth-preview-${{ github.head_ref }}
          component_name: architect-auth
